version: '3.7'
services:
  sum-service:
    image: sum-service:dev
    build:
      context: ./sum-service
      args:
        ENVIRONMENT: development
        NODE_PORT: 8080
        DEBUG_PORT_NAME: 9229
    volumes:
      - ./sum-service/:/home/node/app
    ports:
      - "8080:8080"
      - "9229:9229"
    command: "npm run debug"

  sub-service:
    image: sub-service:dev
    build:
      context: ./sub-service
    volumes:
      - ./sub-service/:/home/node/app
    ports:
      - "8081:8080"
      - "9230:9229"
    command: "npm run debug"

  mongo:
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
      - 8090:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
